### PR TITLE
Optimize memory use by saving the directory in the queue struct

### PR DESCRIPTION
**Pull request by ricardobranco777**

### CODE REVIEW

**Comment by mirtchovski** [comment]
Cool, this looks good, thanks! Can you think of a benchmark that would show improvement? We can add that in too.

**Comment by ricardobranco777** [comment]
With this patch alone I see no big difference with my SSD.  With the other 2 combined I do see an improvement.  Try with this code:

https://gist.github.com/ricardobranco777/3b72b5d6c28897278aed536f7ce1c645

**Comment by mirtchovski** [comment]
Unfortunately I'm not seeing much difference between the two versions. if anything, the new code allocates slightly more and appears slower on large searches. I wrote a simple benchmark that I pushed in, can you post your numbers? i'm on a 4-core macOS machine with a Samsung 850 PRO SSD

```
$ benchcmp /tmp/old.txt /tmp/new.txt 
benchmark           old ns/op     new ns/op     delta
BenchmarkWalk       6824595       6931079       +1.56%
BenchmarkWalk-2     6980005       6880650       -1.42%
BenchmarkWalk-4     6981229       6895778       -1.22%
BenchmarkWalk-8     6988710       6871191       -1.68%

benchmark           old allocs     new allocs     delta
BenchmarkWalk       721            721            +0.00%
BenchmarkWalk-2     721            721            +0.00%
BenchmarkWalk-4     721            721            +0.00%
BenchmarkWalk-8     721            721            +0.00%

benchmark           old bytes     new bytes     delta
BenchmarkWalk       241632        242928        +0.54%
BenchmarkWalk-2     241632        242928        +0.54%
BenchmarkWalk-4     241632        242928        +0.54%
BenchmarkWalk-8     241632        242937        +0.54%
```

Here's the same benchmark ran over `/usr`, a large directory:

```
$ benchcmp /tmp/old.txt /tmp/new.txt 
benchmark           old ns/op     new ns/op     delta
BenchmarkWalk       347827119     353748756     +1.70%
BenchmarkWalk-2     352425784     356742078     +1.22%
BenchmarkWalk-4     350711991     358562111     +2.24%
BenchmarkWalk-8     352004616     378287708     +7.47%

benchmark           old allocs     new allocs     delta
BenchmarkWalk       186323         186323         +0.00%
BenchmarkWalk-2     186323         186323         +0.00%
BenchmarkWalk-4     186323         186323         +0.00%
BenchmarkWalk-8     186323         186323         +0.00%

benchmark           old bytes     new bytes     delta
BenchmarkWalk       19896488      20463325      +2.85%
BenchmarkWalk-2     19896488      20463314      +2.85%
BenchmarkWalk-4     19896466      20463346      +2.85%
BenchmarkWalk-8     19896466      20463341      +2.85%

```

**Comment by ricardobranco777** [comment]
What are the exact commands you used?

**Comment by mirtchovski** [comment]
` go test -test.bench=Bench* -benchmem -cpu 1,2,4,8 > /tmp/old.txt`

then compare the old and new inputs with `benchcmp /tmp/old.txt /tmp/new.txt`

**Comment by ricardobranco777** [comment]
Using Go 1.7.5 on a 4 x Intel(R) Core(TM) i7-3520M CPU @ 2.90GHz and Crucial BX200 SSD:

```benchmark           old ns/op     new ns/op     delta
BenchmarkWalk       465359        466463        +0.24%
BenchmarkWalk-2     606513        550577        -9.22%
BenchmarkWalk-4     521853        516039        -1.11%
BenchmarkWalk-8     523732        531701        +1.52%

benchmark           old allocs     new allocs     delta
BenchmarkWalk       1175           1175           +0.00%
BenchmarkWalk-2     1175           1175           +0.00%
BenchmarkWalk-4     1175           1175           +0.00%
BenchmarkWalk-8     1175           1175           +0.00%

benchmark           old bytes     new bytes     delta
BenchmarkWalk       326792        328504        +0.52%
BenchmarkWalk-2     326792        328504        +0.52%
BenchmarkWalk-4     326793        328505        +0.52%
BenchmarkWalk-8     326793        328506        +0.52%
```

For /usr:

```
benchmark           old ns/op     new ns/op     delta
BenchmarkWalk       458688        468431        +2.12%
BenchmarkWalk-2     624812        512833        -17.92%
BenchmarkWalk-4     534288        538945        +0.87%
BenchmarkWalk-8     535447        517107        -3.43%

benchmark           old allocs     new allocs     delta
BenchmarkWalk       1175           1175           +0.00%
BenchmarkWalk-2     1175           1175           +0.00%
BenchmarkWalk-4     1175           1175           +0.00%
BenchmarkWalk-8     1175           1175           +0.00%

benchmark           old bytes     new bytes     delta
BenchmarkWalk       326792        328504        +0.52%
BenchmarkWalk-2     326792        328504        +0.52%
BenchmarkWalk-4     326792        328505        +0.52%
BenchmarkWalk-8     326793        328505        +0.52%
```

**Comment by mirtchovski** [comment]
The numbers for `/usr` don't look right, the number of allocs should be much bigger... unless your /usr is very empty :)

**Comment by ricardobranco777** [comment]
I used this command for /usr:

`go test -test.bench=Bench* -benchmem -cpu 1,2,4,8 -args /usr`

**Comment by mirtchovski** [comment]
You'll need to edit the benchmark function in walk_test.go. it's really
basic.

**Comment by ricardobranco777** [comment]
```
benchmark           old ns/op     new ns/op     delta
BenchmarkWalk       480110638     505404450     +5.27%
BenchmarkWalk-2     566795489     678990175     +19.79%
BenchmarkWalk-4     633317641     638271074     +0.78%
BenchmarkWalk-8     729015263     584787484     -19.78%

benchmark           old allocs     new allocs     delta
BenchmarkWalk       1526590        1526590        +0.00%
BenchmarkWalk-2     1526590        1526590        +0.00%
BenchmarkWalk-4     1526590        1526590        +0.00%
BenchmarkWalk-8     1526593        1526595        +0.00%

benchmark           old bytes     new bytes     delta
BenchmarkWalk       207995184     211544008     +1.71%
BenchmarkWalk-2     207995320     211544160     +1.71%
BenchmarkWalk-4     207995360     211544296     +1.71%
BenchmarkWalk-8     207995688     211544728     +1.71%
```

**Pull request closed without merging**
